env:
    browser: false
    es6: true
    node: true
extends:
- "eslint:recommended"
- "google"
- "eslint-config-prettier"
parserOptions:
  ecmaVersion: 8
rules:
  sort-keys: 
    - "error"
    - "asc" 
    - {"natural": true}