language: node_js
stages:
  - Test
  - name: Publish
    if: branch = master
jobs:
  include:
    - stage: Test
      node_js:
        - lts/*
      cache:
        npm: false
        directories:
          - "~/.pnpm-store"
      before_install:
        - curl -L https://unpkg.com/@pnpm/self-installer | node
        - pnpm config set store-dir ~/.pnpm-store
      install:
        - pnpm install
      before_script:
        - pnpm check-lint
        - pnpm check-pretty
      script:
        - pnpm test
    - stage: Publish
      node_js: lts/*
      cache:
        npm: false
        directories:
          - "~/.pnpm-store"
      before_install:
        - curl -L https://unpkg.com/@pnpm/self-installer | node
        - pnpm config set store-dir ~/.pnpm-store
      install:
        - pnpm install
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - pnpx semantic-release
